name = "pulumi"
type = "cli"

[platform.macos]
archive-prefix = "pulumi"
download-file = "pulumi-v{version}-darwin-{arch}.tar.gz"

[platform.linux]
archive-prefix = "pulumi"
download-file = "pulumi-v{version}-linux-{arch}.tar.gz"

[install]
download-url = "https://github.com/pulumi/pulumi/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x64"

[resolve]
git-url = "https://github.com/pulumi/pulumi"
